### ISSUE TITLE
Invalid data type when submit to leaderboard

### ISSUE THREAD

**Issue by cnut1648** [THU-KEG/MAVEN-dataset#12]
Hi, I would like to submit to the leaderboard. I ran the BERT+CRF model and produced the `result.jsonl`. But when I tried to submit to leaderboard at [codalab](https://competitions.codalab.org/competitions/27320#participate-submit_results) I got the following issue

> invalid data type ()

I am wondering what should I do in this case? Thank you!

**Comment by Bakser** [comment]
Hi, please check the "Submission Format" instruction in the CodaLab. The submitted file is needed to be compressed into a `.zip` file.

**Comment by cnut1648** [comment]
Thanks! That works! I have another question, what is the score of in the submission?
![image](https://user-images.githubusercontent.com/37067883/143982291-aff11b30-6430-4d73-9563-090448b6e05e.png)

In the evaluation section of the CodaLab, it has
> The submissions are evaluated with precision, recall, and F1 (micro and macro averaged). The evaluation script is available at the Github repository. For more details, please refer to the paper.

But [the script](https://github.com/THU-KEG/MAVEN-dataset/blob/main/evaluate.py#L76-L88) actually would write all of F1 P, R, etc instead of a single number. Thus I am wondering what that number ("score") represents. Thank you!

**Comment by Bakser** [comment]
The score here is the micro F1 for ranking. To get all the metrics, you can view the scoring output log or submit your results to the leaderboard.

**Comment by cnut1648** [comment]
Hi sorry to bother you again, when I try to submit today, I got
> Sorry, failed to upload file.

error, even if I did submit with a `.zip` file. Do you know what might cause this issue? The file size is ~2MB.

**Comment by Bakser** [comment]
Sorry I haven't met this issue. You may check your network connection and ask this question in CodaLab user communities.
