### ISSUE TITLE
tokenization

### ISSUE THREAD

**Issue by sky-snow** [THU-KEG/MAVEN-dataset#14]
您好，请问数据集中分词使用的工具是什么呀，我使用斯坦福的分词工具，输出的token长度会出现不一致的问题

**Comment by Bakser** [comment]
您好，数据集分词使用的是nltk。不过我们也手动纠正了一些影响标注内容边界的分词错误，因此现在使用nltk也无法得到完全一致的结果。您自己实现模型时使用任何分词方案都没有问题，只要提交的结果的offset是统一到我们的分词口径就好。
