### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Yyy11181** [THU-KEG/MAVEN-dataset#15]
hello, 你好 negative_triggers 在数据集中的意义是什么啊

**Comment by Bakser** [comment]
您好，抱歉没有及时回复。这个问题可以这么理解。在真实的事件检测应用中，模型不仅要为触发词（trigger）分类事件类型，还要判断数据集中哪些词是触发词，哪些词不是。negative triggers就是不是触发词的那些词，在训练中作为负例使用。如果模型没有区分正负例的能力，而只有给正例分类的能力，是没有办法在实际情况中使用的。
