### ISSUE TITLE
bert-crf里面，评估阶段f1值为什么变成0？而且没有保存到结果里面

### ISSUE THREAD

**Issue by NLPKingSolomon** [THU-KEG/MAVEN-dataset#16]

**Comment by NLPKingSolomon** [comment]
INFO - transformers.tokenization_utils -   Model name './MAVEN' not found in model shortcut name list

**Comment by NLPKingSolomon** [comment]
![image](https://user-images.githubusercontent.com/93171304/207820968-e9deaeb4-8207-4c4a-b697-cd28da20701d.png)

**Comment by Bakser** [comment]
您好，抱歉没有及时回复。我试了下没能复现这个情况，可能是您的环境的特殊问题。您可以尝试下我们最近发布的[OmniEvent工具包](https://github.com/THU-KEG/OmniEvent)中的实现，应当会更加稳定。
