### ISSUE TITLE
数据的统计结果好像不对？

### ISSUE THREAD

**Issue by Wangpeiyi9979** [THU-KEG/MAVEN-dataset#2]

**Comment by Wangpeiyi9979** [comment]
数据集的trigger数量以及Negative数量和原始论文数量略有差异
![image](https://user-images.githubusercontent.com/42565075/100853370-a74be200-34c2-11eb-8029-077648e076e6.png)
![image](https://user-images.githubusercontent.com/42565075/100853765-1a555880-34c3-11eb-8d3d-7371ad9278d3.png)
![image](https://user-images.githubusercontent.com/42565075/100853738-0f022d00-34c3-11eb-9e6a-34c4ce84b986.png)

**Comment by Bakser** [comment]
您好，感谢对我们工作的兴趣。
这个数量与我们[论文](https://arxiv.org/pdf/2004.13590.pdf)是一致的。
您看的这个统计可能来自我们的[旧版论文](https://arxiv.org/pdf/2004.13590v1.pdf)，当时还没有完成全部数据清洗，统计上会有一些差异。
