### ISSUE TITLE
测评时认为trigger是已知的还是未知的？

### ISSUE THREAD

**Issue by scarydemon2** [THU-KEG/MAVEN-dataset#6]
比如BERT+CRFbaseline在测评的时候没有使用trigger的标注信息。而DMBERTbaseline在测评的时候是按照trigger词将句子分成了两段。虽然test集中给定了trigger的offset，但是这两个模型显然放在一起比较不是很公平。官方比较推荐的测评方法是什么样的？

**Comment by Bakser** [comment]
您好，我们所有评测里trigger都是未知的。CRF方法是按序列标注进行的trigger预测。而DMBERT是按token-level classification的方法进行的预测，因此需要给定一个待分类的candidate再进行分类，这个candidate不一定是trigger。

我理解您的问题是说DMBERT只能在给定的candidate里做分类，而CRF有可能预测出不在我们给定的candidate set里的trigger，这样比较起来不太公平？这个问题可以注意下[这部分代码](https://github.com/THU-KEG/MAVEN-dataset/blob/a0b454cad65518a2ac72e0530351f7e5bd334219/baselines/BERT%2BCRF/BERT-CRF-MAVEN/run_maven.py#L576-L603)，我们的BERT+CRF baseline生成提交到CodaLab的结果时是对齐到给定的candidate set的，和DMBERT是一样的。训练过程中验证集上使用的是seqeval的metric，虽然没有对齐到candidate set，但在我们实验中这个metric和对齐到candidate set的方式差距非常小。
