### ISSUE TITLE
关于如何添加negative trigger的问题

### ISSUE THREAD

**Issue by scarydemon2** [THU-KEG/MAVEN-dataset#7]
作者你好，我在论文5.1节第二段看到“Conventionally, the existing ED datasets only provide the standard annotation of positive instances (the annotated event triggers) and researchers will sample the negative instances (non-trigger words or phrases) by themselves, which may lead to potential unfair comparisons between different methods”
    想请问作者，ACE数据集里是否也有这样的操作？如果有的话可否提供一两篇包含这种添加negative trigger做法的论文，因为自己目前在写毕业论文，想同时使用ACE和MAVEN数据集，但是两个数据集的测评方法不同，所以感到很棘手。十分感谢！

**Comment by Bakser** [comment]
您好，据我所知ACE数据集里没有与我们添加negative trigger的方法完全一致的工作。您可以按照我们文章中描述的方法，用nltk和FrameNet为ACE按照我们的策略采样negative trigger。
