### ISSUE TITLE
您好，我想询问怎么进行trigger identify这部分

### ISSUE THREAD

**Issue by Macvh** [THU-KEG/MAVEN-dataset#8]
关于DMBERT，是在已知trigger的情况下进行事件分类的吗，如何才能知道trigger是哪个呢

**Comment by WBWhiteBeard** [comment]
这个整个分享的代码，是不是没有 触发词抽取 的这一部分啊。
只有类型识别，是么

**Comment by Bakser** [comment]
您好，不是的，可以参考我们论文第二节的后半部分，我们的baseline都没有单独做identification步骤，而是统一在classification步骤做了触发词识别和事件类别分类。具体来说，我们有168个事件类别，而模型要对每个trigger candidate（可能是trigger也可能不是）做168+1分类，多出来的一类是“None”，意思就是这个candidate不是触发词。
